#!/bin/bash
git add . #komanda "uzmanāmo" mapju pievienošana
git config --global user.name ViestursA
git config --global user.email akmentinsviesturs@gmail.com
git commit -m "Class_04b"
git push origin main
